name: Build Docker Images

on:
  workflow_run:
    workflows: ["Pre-build checks"]
    types:
      - completed

permissions:
  checks: write
  contents: read

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script: [ 'build-base-k8s-jenkins-agent.sh', 'build-base-swarm-jenkins-agent.sh', 'build-edt-swarm-agent.sh', 'build-oscript-k8s-agent.sh', 'build-oscript-swarm-agent.sh', 'build-server.sh' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        # Получаем рефы для pull-реквеста
        ref: ${{ github.event.workflow_run.head_branch }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker images
      env:
        DOCKER_REGISTRY_URL: 'localhost:5000'
        DOCKER_LOGIN: ""
        DOCKER_PASSWORD: ""
        ONEC_USERNAME: ${{ secrets.ONEC_USERNAME}}
        ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD}}
        ONEC_VERSION: '8.3.24.1624'
        EDT_VERSION: '2023.3.6'
      run: |
        docker run -d -p 5000:5000 --name registry registry:2
        ./${{ matrix.script }}
    - name: Set Job Status
      if: always()
      uses: s4u/set-job-status-action@v1
      with:
        status: ${{ job.status }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
