name: Build Docker Images

on:
  push:
    branches: [ feature/first-bit]
  pull_request:
    branches: [ feature/first-bit]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker images
      env:
        DOCKER_REGISTRY_URL: 'localhost:5000'
        DOCKER_LOGIN: ""
        DOCKER_PASSWORD: ""
        ONEC_USERNAME: ${{ secrets.ONEC_USERNAME}}
        ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD}}
        ONEC_VERSION: '8.3.18.1520'
      run: |
        docker run -d -p 5000:5000 --name registry registry:2
        ./build-base-swarm-jenkins-agent.sh
        
