name: Build Docker Images

on:
  push:
    branches: [ feature/first-bit]
  pull_request:
    branches: [ feature/first-bit]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        script: [ 'build-base-k8s-jenkins-agent.sh', 'build-base-k8s-jenkins-agent.sh', 'build-crs.sh', 'build-edt-k8s-agent.sh', 'build-edt-swarm-agent.sh', 'build-oscript-k8s-agent.sh', 'build-oscript-swarm-agent.sh', 'build-server.sh' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker images
      env:
        DOCKER_REGISTRY_URL: 'localhost:5000'
        DOCKER_LOGIN: ""
        DOCKER_PASSWORD: ""
        ONEC_USERNAME: ${{ secrets.ONEC_USERNAME}}
        ONEC_PASSWORD: ${{ secrets.ONEC_PASSWORD}}
        ONEC_VERSION: '8.3.24.1624'
        EDT_VERSION: '2021.2.7'
      run: |
        docker run -d -p 5000:5000 --name registry registry:2
        ./${{ matrix.script }}
        
